// This file contains constant data used throughout the application.
// Centralizing constants makes them easy to manage and update.

import type { PlaygroundApp } from './types';
import { MessageSquare, Image, Video, Mic, BrainCircuit, ScanSearch, Feather, ShieldCheck, Lightbulb } from 'lucide-react';

// Defines the list of AI-powered applications available in the "AI Playground".
// Each object contains metadata for an app, which is used to render its card and launch the tool.
export const PLAYGROUND_APPS: PlaygroundApp[] = [
  {
    id: 'chatbot',
    name: 'ZOSO AI',
    description: "Ask me anything about my skills, projects, or tech in general. Connects to live search tools for up-to-date info.",
    icon: MessageSquare, // Icon from the lucide-react library.
  },
  {
    id: 'imageGen',
    name: 'AI Image Generator',
    description: 'Generate high-quality images from text prompts. Choose your aspect ratio and bring your ideas to life.',
    icon: Image,
  },
  {
    id: 'complexSolver',
    name: 'Complex Problem Solver',
    description: 'Pose a complex coding or system design problem and get a detailed, well-reasoned solution from an advanced model.',
    icon: BrainCircuit,
  },
  {
    id: 'projectAnalyzer',
    name: 'Project Analyzer',
    description: 'Upload an image of a UI mockup or a project screenshot for AI-powered analysis and feedback.',
    icon: ScanSearch,
  },
  {
    id: 'humanizer',
    name: 'Humanizer AI',
    description: 'Rewrite AI-generated or formal text to sound more natural, engaging, and human-like. Improve clarity and flow.',
    icon: Feather,
  },
  {
    id: 'aiDetector',
    name: 'AI Text Detector',
    description: 'Analyze text to determine if it was likely written by a human or generated by an AI. Get a confidence score and reasoning.',
    icon: ShieldCheck,
  },
  {
    id: 'promptEnhancer',
    name: 'Prompt Enhancer',
    description: 'Turn a simple idea into a detailed, rich prompt perfect for generating high-quality AI images or text.',
    icon: Lightbulb,
  },
  {
    id: 'videoGen',
    name: 'AI Video Generator',
    description: 'Create short videos from text prompts or by animating a static image. Powered by an advanced video generation model.',
    icon: Video,
  },
  {
    id: 'liveConvo',
    name: 'Live Conversation',
    description: 'Have a real-time voice conversation with an AI assistant. Experience ultra-low latency interaction.',
    icon: Mic,
  },
];
